
package Interfaz;

import JavaEatF.Cliente;
import JavaEatF.Empresa;
import JavaEatF.Metodos;
import static JavaEatF.Metodos.buenaFecha;
import JavaEatF.Particular;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author tgarc
 */
public class DatosCuenta extends javax.swing.JFrame {

    private App appParticulares;
    private MenuInicial principal;
    private Cliente cliente;
    private ArrayList<Cliente> clientes;
    
    /**
     * Creates new form DatosCuenta
     * @param cliente
     * @param ventana
     */
    public DatosCuenta(Cliente cliente, App ventana) {
        appParticulares = ventana;
        appParticulares.setVisible(false);
        this.cliente = cliente;
        System.out.println(cliente);
        this.setVisible(true);
        initComponents();

        TextFieldNombre3.setText(cliente.getNombre());
        TextFieldCorreo3.setText(cliente.getCorreo());
        TextFieldContraseña3.setText(cliente.getClave());
        TextFieldTitular3.setText(cliente.getTitularTarjeta());
        TextFieldCalle3.setText(cliente.getCalle());
        jFormattedTextField11.setText(cliente.getCodigoPostal());
        jFormattedTextField12.setText(cliente.getNumeroTarjeta());
        FormattedTextFieldTelefono3.setText(cliente.getTelefono());
        jFormattedTextField10.setText(String.valueOf(cliente.getNumeroCalle()));
        TextFieldCiudad3.setText(cliente.getCiudad());
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        TextFieldFecha3.setText((cliente.getFechaCaducidad()).format(formatter));

        if (cliente instanceof Particular) {
            Particular particular = (Particular) cliente;
            TextFieldWeb3.setVisible(false);
            LabelWeb3.setVisible(false);
            LabelVar3.setText("DNI");
            TextFieldVar3.setText(((Particular) cliente).getDni());
        } else if (cliente instanceof Empresa) {
            Empresa empresa = (Empresa) cliente;
            TextFieldWeb3.setVisible(true);
            LabelWeb3.setVisible(true);
            LabelVar3.setText("CIF");
            TextFieldVar3.setText(((Empresa) cliente).getCif());
            TextFieldWeb3.setText(empresa.getWeb());
        }
    }   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        LabelRegistrarse3 = new javax.swing.JLabel();
        LabelVar3 = new javax.swing.JLabel();
        LabelCorreo3 = new javax.swing.JLabel();
        LabelNombre3 = new javax.swing.JLabel();
        LabelContraseña3 = new javax.swing.JLabel();
        LabelTarjeta3 = new javax.swing.JLabel();
        LabelDireccion3 = new javax.swing.JLabel();
        LabelTelefono3 = new javax.swing.JLabel();
        TextFieldRegistrar3 = new javax.swing.JTextField();
        TextFieldNombre3 = new javax.swing.JTextField();
        TextFieldVar3 = new javax.swing.JTextField();
        TextFieldCorreo3 = new javax.swing.JTextField();
        TextFieldTitular3 = new javax.swing.JTextField();
        TextFieldCalle3 = new javax.swing.JTextField();
        LabelWeb3 = new javax.swing.JLabel();
        TextFieldWeb3 = new javax.swing.JTextField();
        TextFieldContraseña3 = new javax.swing.JTextField();
        FormattedTextFieldTelefono3 = new javax.swing.JFormattedTextField();
        TextFieldCiudad3 = new javax.swing.JTextField();
        TextFieldFecha3 = new javax.swing.JFormattedTextField();
        jFormattedTextField10 = new javax.swing.JFormattedTextField();
        jFormattedTextField11 = new javax.swing.JFormattedTextField();
        jFormattedTextField12 = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        LabelRegistrarse3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LabelRegistrarse3.setText("DATOS DE LA CUENTA");

        LabelVar3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelVar3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelVar3.setText("DNI");

        LabelCorreo3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelCorreo3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelCorreo3.setText("CORREO");
        LabelCorreo3.setToolTipText("");

        LabelNombre3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelNombre3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelNombre3.setText("NOMBRE");

        LabelContraseña3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelContraseña3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelContraseña3.setText("CONTRASEÑA");

        LabelTarjeta3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTarjeta3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelTarjeta3.setText("TARJETA DE CRÉDITO");

        LabelDireccion3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelDireccion3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelDireccion3.setText("DIRECCIÓN");

        LabelTelefono3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTelefono3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelTelefono3.setText("TELÉFONO");

        TextFieldRegistrar3.setEditable(false);
        TextFieldRegistrar3.setBackground(new java.awt.Color(72, 192, 192));
        TextFieldRegistrar3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TextFieldRegistrar3.setForeground(new java.awt.Color(255, 255, 255));
        TextFieldRegistrar3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldRegistrar3.setText("MODIFICAR");
        TextFieldRegistrar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TextFieldRegistrar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextFieldRegistrar3MouseClicked(evt);
            }
        });
        TextFieldRegistrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldRegistrar3ActionPerformed(evt);
            }
        });

        TextFieldNombre3.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        TextFieldVar3.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        TextFieldCorreo3.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        TextFieldTitular3.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        TextFieldTitular3.setToolTipText("Nombre del titular");
        TextFieldTitular3.setBorder(javax.swing.BorderFactory.createTitledBorder("Titular"));

        TextFieldCalle3.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        TextFieldCalle3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Calle")));

        LabelWeb3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelWeb3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelWeb3.setText("WEB");

        TextFieldWeb3.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        TextFieldContraseña3.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        FormattedTextFieldTelefono3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        FormattedTextFieldTelefono3.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        TextFieldCiudad3.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        TextFieldCiudad3.setBorder(javax.swing.BorderFactory.createTitledBorder("Ciudad"));

        TextFieldFecha3.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de caducidad"));
        try {
            TextFieldFecha3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TextFieldFecha3.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jFormattedTextField10.setBorder(javax.swing.BorderFactory.createTitledBorder("Número"));
        jFormattedTextField10.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jFormattedTextField11.setBorder(javax.swing.BorderFactory.createTitledBorder("C. Postal"));
        jFormattedTextField11.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jFormattedTextField12.setBorder(javax.swing.BorderFactory.createTitledBorder("Número"));
        jFormattedTextField12.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(TextFieldTitular3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(TextFieldFecha3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(LabelTarjeta3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(176, 176, 176))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(LabelNombre3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelVar3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(LabelContraseña3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelTelefono3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldNombre3, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(FormattedTextFieldTelefono3)
                            .addComponent(TextFieldContraseña3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldWeb3)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelCorreo3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelWeb3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(TextFieldCorreo3)
                            .addComponent(TextFieldVar3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(TextFieldCalle3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedTextField11, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(TextFieldCiudad3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldRegistrar3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelRegistrarse3, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelDireccion3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(34, 34, 34))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(LabelRegistrarse3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(LabelVar3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(LabelNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextFieldNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldVar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelContraseña3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCorreo3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldCorreo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldContraseña3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(LabelTelefono3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FormattedTextFieldTelefono3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(LabelWeb3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldWeb3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(LabelDireccion3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFormattedTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextFieldCalle3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TextFieldCiudad3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFormattedTextField10)))
                .addGap(19, 19, 19)
                .addComponent(LabelTarjeta3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldTitular3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldFecha3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField12))
                .addGap(29, 29, 29)
                .addComponent(TextFieldRegistrar3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
            // TODO add your handling code here:
            MenuInicial menuInicial = new MenuInicial();
            
        } catch (IOException ex) {
            Logger.getLogger(DatosCuenta.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DatosCuenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosed

    private void TextFieldRegistrar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldRegistrar3MouseClicked

        try {
            clientes = Metodos.LeerClientes();
            } catch (IOException ex) {
                     Logger.getLogger(DatosCuenta.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                     Logger.getLogger(DatosCuenta.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        Cliente c = Metodos.consultaClientePorCorreo(cliente.getCorreo(), clientes);

        clientes.remove(c);

        String cif = TextFieldVar3.getText();
        String nombre = TextFieldNombre3.getText();
        String correo = TextFieldCorreo3.getText();
        String clave = TextFieldContraseña3.getText();
        String telefono = FormattedTextFieldTelefono3.getText();
        String calle = TextFieldCalle3.getText();
        String numeroCalle = jFormattedTextField10.getText();
        String codigoPostal = jFormattedTextField11.getText();
        String ciudad = TextFieldCiudad3.getText();
        String titularTarjeta = TextFieldTitular3.getText();
        String numeroTarjeta = jFormattedTextField12.getText();
        String fechaCaducidadTxt = (String) TextFieldFecha3.getValue();
        String web = TextFieldWeb3.getText();

        if (cif.isEmpty() || nombre.isEmpty() || correo.isEmpty() || clave.isEmpty() || telefono.isEmpty()
            || calle.isEmpty() || numeroCalle.isEmpty() || codigoPostal.isEmpty() || ciudad.isEmpty()) {

            JOptionPane.showMessageDialog(rootPane, "Rellene todos los campos.");

        } else if (fechaCaducidadTxt == null) {

            JOptionPane.showMessageDialog(rootPane, "Introduce una fecha válida.");

        } else if ((codigoPostal.length() < 5) || (Integer.parseInt(codigoPostal) <0)) {

            JOptionPane.showMessageDialog(rootPane, "Introduce un código postal válido.");

        } else if ((numeroTarjeta.length() != 16) || (Long.parseLong(numeroTarjeta)<0 )) {

            JOptionPane.showMessageDialog(rootPane, "Introduce un número de tarjeta válido.");

        } else if (Integer.parseInt(telefono)<0) {

            JOptionPane.showMessageDialog(rootPane, "Introduce un telefono válido.");

        } else if (Integer.parseInt(numeroCalle)< 0) {

            JOptionPane.showMessageDialog(rootPane, "Introduce un numero de calle válido.");

        } else if (((Metodos.consultaClientePorCorreo(correo, clientes) != null))) {
            
            JOptionPane.showMessageDialog(rootPane, "Cuenta ya registrada.");
            
        }else {

            String[] partes = fechaCaducidadTxt.split("/");
            int d1 = Integer.parseInt(partes[0]);
            int m1 = Integer.parseInt(partes[1]);
            int a1 = Integer.parseInt(partes[2]);

            if (!buenaFecha(d1, m1, a1)) {
                JOptionPane.showMessageDialog(rootPane, "Introduce una fecha válida.");
            } else {
                LocalDate fechaCaducidad = LocalDate.of(a1, m1, d1);

                if (cliente instanceof Particular) {
                    String dni = TextFieldVar3.getText();

                    Particular par = new Particular(dni, nombre, correo, clave, calle, Integer.parseInt(numeroCalle.trim()), codigoPostal, ciudad, telefono,
                        titularTarjeta, numeroTarjeta, fechaCaducidad);

                    System.out.println(par.toString() + "|Particular");
                    
                    clientes.add(par);
                    Metodos.RegistrarClientes(clientes);
                    JOptionPane.showMessageDialog(rootPane, "Has modificado tus datos.");

                } else if (cliente instanceof Empresa) {
                    Empresa em = new Empresa(cif, nombre, correo, clave, calle, Integer.parseInt(numeroCalle), codigoPostal, ciudad, telefono, web,
                        titularTarjeta, numeroTarjeta, fechaCaducidad);

                    if (web.isEmpty()) {
                        JOptionPane.showMessageDialog(rootPane, "Rellene todos los campos.");
                    }
                    else {
                        System.out.println(em.toString() + "|Empresa");
                        
                        clientes.add(em);
                        Metodos.RegistrarClientes(clientes);
                        JOptionPane.showMessageDialog(rootPane, "Has modificado tus datos.");

                    }
                }
            }
        }
    }//GEN-LAST:event_TextFieldRegistrar3MouseClicked

    private void TextFieldRegistrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldRegistrar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldRegistrar3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxTipo;
    private javax.swing.JComboBox<String> ComboBoxTipo1;
    private javax.swing.JComboBox<String> ComboBoxTipo2;
    private javax.swing.JFormattedTextField FormattedTextFieldTelefono;
    private javax.swing.JFormattedTextField FormattedTextFieldTelefono1;
    private javax.swing.JFormattedTextField FormattedTextFieldTelefono2;
    private javax.swing.JFormattedTextField FormattedTextFieldTelefono3;
    private javax.swing.JLabel LabelContraseña;
    private javax.swing.JLabel LabelContraseña1;
    private javax.swing.JLabel LabelContraseña2;
    private javax.swing.JLabel LabelContraseña3;
    private javax.swing.JLabel LabelCorreo;
    private javax.swing.JLabel LabelCorreo1;
    private javax.swing.JLabel LabelCorreo2;
    private javax.swing.JLabel LabelCorreo3;
    private javax.swing.JLabel LabelDireccion;
    private javax.swing.JLabel LabelDireccion1;
    private javax.swing.JLabel LabelDireccion2;
    private javax.swing.JLabel LabelDireccion3;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelNombre1;
    private javax.swing.JLabel LabelNombre2;
    private javax.swing.JLabel LabelNombre3;
    private javax.swing.JLabel LabelRegistrarse;
    private javax.swing.JLabel LabelRegistrarse1;
    private javax.swing.JLabel LabelRegistrarse2;
    private javax.swing.JLabel LabelRegistrarse3;
    private javax.swing.JLabel LabelTarjeta;
    private javax.swing.JLabel LabelTarjeta1;
    private javax.swing.JLabel LabelTarjeta2;
    private javax.swing.JLabel LabelTarjeta3;
    private javax.swing.JLabel LabelTelefono;
    private javax.swing.JLabel LabelTelefono1;
    private javax.swing.JLabel LabelTelefono2;
    private javax.swing.JLabel LabelTelefono3;
    private javax.swing.JLabel LabelVar;
    private javax.swing.JLabel LabelVar1;
    private javax.swing.JLabel LabelVar2;
    private javax.swing.JLabel LabelVar3;
    private javax.swing.JLabel LabelWeb;
    private javax.swing.JLabel LabelWeb1;
    private javax.swing.JLabel LabelWeb2;
    private javax.swing.JLabel LabelWeb3;
    private javax.swing.JTextField TextFieldBorrar;
    private javax.swing.JTextField TextFieldBorrar1;
    private javax.swing.JTextField TextFieldBorrar2;
    private javax.swing.JTextField TextFieldCalle;
    private javax.swing.JTextField TextFieldCalle1;
    private javax.swing.JTextField TextFieldCalle2;
    private javax.swing.JTextField TextFieldCalle3;
    private javax.swing.JTextField TextFieldCiudad;
    private javax.swing.JTextField TextFieldCiudad1;
    private javax.swing.JTextField TextFieldCiudad2;
    private javax.swing.JTextField TextFieldCiudad3;
    private javax.swing.JTextField TextFieldContraseña;
    private javax.swing.JTextField TextFieldContraseña1;
    private javax.swing.JTextField TextFieldContraseña2;
    private javax.swing.JTextField TextFieldContraseña3;
    private javax.swing.JTextField TextFieldCorreo;
    private javax.swing.JTextField TextFieldCorreo1;
    private javax.swing.JTextField TextFieldCorreo2;
    private javax.swing.JTextField TextFieldCorreo3;
    private javax.swing.JFormattedTextField TextFieldFecha;
    private javax.swing.JFormattedTextField TextFieldFecha1;
    private javax.swing.JFormattedTextField TextFieldFecha2;
    private javax.swing.JFormattedTextField TextFieldFecha3;
    private javax.swing.JTextField TextFieldNombre;
    private javax.swing.JTextField TextFieldNombre1;
    private javax.swing.JTextField TextFieldNombre2;
    private javax.swing.JTextField TextFieldNombre3;
    private javax.swing.JTextField TextFieldRegistrar;
    private javax.swing.JTextField TextFieldRegistrar1;
    private javax.swing.JTextField TextFieldRegistrar2;
    private javax.swing.JTextField TextFieldRegistrar3;
    private javax.swing.JTextField TextFieldTitular;
    private javax.swing.JTextField TextFieldTitular1;
    private javax.swing.JTextField TextFieldTitular2;
    private javax.swing.JTextField TextFieldTitular3;
    private javax.swing.JTextField TextFieldVar;
    private javax.swing.JTextField TextFieldVar1;
    private javax.swing.JTextField TextFieldVar2;
    private javax.swing.JTextField TextFieldVar3;
    private javax.swing.JTextField TextFieldWeb;
    private javax.swing.JTextField TextFieldWeb1;
    private javax.swing.JTextField TextFieldWeb2;
    private javax.swing.JTextField TextFieldWeb3;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField10;
    private javax.swing.JFormattedTextField jFormattedTextField11;
    private javax.swing.JFormattedTextField jFormattedTextField12;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JFormattedTextField jFormattedTextField6;
    private javax.swing.JFormattedTextField jFormattedTextField7;
    private javax.swing.JFormattedTextField jFormattedTextField8;
    private javax.swing.JFormattedTextField jFormattedTextField9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
