package Interfaz;

import JavaEatF.Cliente;
import JavaEatF.Empresa;
import JavaEatF.Metodos;
import static JavaEatF.Metodos.buenaFecha;
import JavaEatF.Particular;
import java.awt.HeadlessException;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**Crea la ventana para el registro de usuarios
 *
 * @author Tatiana Garcia 
 */
public class MenuRegistrar extends javax.swing.JFrame {
    
    private MenuInicial principal;
    private String tipo = "";
    private ArrayList<Cliente> clientes;
    
    /**Crea la ventana
     * Creates new form MenuRegistrar
     */
    public MenuRegistrar(MenuInicial ventana) throws IOException, FileNotFoundException, ClassNotFoundException {
        
        principal = ventana;
        principal.setVisible(false);
        this.setVisible(true);
        initComponents();
        LabelWeb.setVisible(false);
        TextFieldWeb.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelRegistrarse = new javax.swing.JLabel();
        ComboBoxTipo = new javax.swing.JComboBox<>();
        LabelVar = new javax.swing.JLabel();
        LabelCorreo = new javax.swing.JLabel();
        LabelNombre = new javax.swing.JLabel();
        LabelContraseña = new javax.swing.JLabel();
        LabelTarjeta = new javax.swing.JLabel();
        LabelDireccion = new javax.swing.JLabel();
        LabelTelefono = new javax.swing.JLabel();
        TextFieldBorrar = new javax.swing.JTextField();
        TextFieldRegistrar = new javax.swing.JTextField();
        TextFieldNombre = new javax.swing.JTextField();
        TextFieldVar = new javax.swing.JTextField();
        TextFieldCorreo = new javax.swing.JTextField();
        TextFieldTitular = new javax.swing.JTextField();
        TextFieldCalle = new javax.swing.JTextField();
        LabelWeb = new javax.swing.JLabel();
        TextFieldWeb = new javax.swing.JTextField();
        TextFieldContraseña = new javax.swing.JTextField();
        FormattedTextFieldTelefono = new javax.swing.JFormattedTextField();
        TextFieldCiudad = new javax.swing.JTextField();
        TextFieldFecha = new javax.swing.JFormattedTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        LabelRegistrarse.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LabelRegistrarse.setText("REGISTRARSE");

        ComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Particular", "Empresa" }));
        ComboBoxTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxTipoActionPerformed(evt);
            }
        });

        LabelVar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelVar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelVar.setText("DNI");

        LabelCorreo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelCorreo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelCorreo.setText("CORREO");
        LabelCorreo.setToolTipText("");

        LabelNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelNombre.setText("NOMBRE");

        LabelContraseña.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelContraseña.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelContraseña.setText("CONTRASEÑA");

        LabelTarjeta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTarjeta.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelTarjeta.setText("TARJETA DE CRÉDITO");

        LabelDireccion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelDireccion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelDireccion.setText("DIRECCIÓN");

        LabelTelefono.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelTelefono.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelTelefono.setText("TELÉFONO");

        TextFieldBorrar.setEditable(false);
        TextFieldBorrar.setBackground(new java.awt.Color(72, 192, 192));
        TextFieldBorrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TextFieldBorrar.setForeground(new java.awt.Color(255, 255, 255));
        TextFieldBorrar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldBorrar.setText("BORRAR");
        TextFieldBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TextFieldBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextFieldBorrarMouseClicked(evt);
            }
        });

        TextFieldRegistrar.setEditable(false);
        TextFieldRegistrar.setBackground(new java.awt.Color(72, 192, 192));
        TextFieldRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TextFieldRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        TextFieldRegistrar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldRegistrar.setText("REGISTRAR");
        TextFieldRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TextFieldRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TextFieldRegistrarMouseClicked(evt);
            }
        });
        TextFieldRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldRegistrarActionPerformed(evt);
            }
        });

        TextFieldNombre.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        TextFieldVar.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        TextFieldCorreo.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        TextFieldTitular.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        TextFieldTitular.setToolTipText("Nombre del titular");
        TextFieldTitular.setBorder(javax.swing.BorderFactory.createTitledBorder("Titular"));

        TextFieldCalle.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        TextFieldCalle.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Calle")));

        LabelWeb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LabelWeb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelWeb.setText("WEB");

        TextFieldWeb.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        TextFieldContraseña.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        FormattedTextFieldTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        FormattedTextFieldTelefono.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        TextFieldCiudad.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        TextFieldCiudad.setBorder(javax.swing.BorderFactory.createTitledBorder("Ciudad"));

        TextFieldFecha.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de caducidad"));
        try {
            TextFieldFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TextFieldFecha.setHorizontalAlignment(javax.swing.JTextField.TRAILING);

        jFormattedTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder("Número"));
        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jFormattedTextField2.setBorder(javax.swing.BorderFactory.createTitledBorder("C. Postal"));
        jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jFormattedTextField3.setBorder(javax.swing.BorderFactory.createTitledBorder("Número"));
        jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TextFieldTitular, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TextFieldFecha))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(176, 176, 176))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelVar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(LabelContraseña, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelTelefono, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(FormattedTextFieldTelefono)
                            .addComponent(TextFieldContraseña, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldWeb)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelCorreo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelWeb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(TextFieldCorreo)
                            .addComponent(TextFieldVar)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(TextFieldCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(TextFieldCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TextFieldRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextFieldBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(ComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(LabelRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(LabelVar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(LabelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldVar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FormattedTextFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LabelWeb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldWeb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(LabelDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextFieldCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TextFieldCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jFormattedTextField1)))
                .addGap(19, 19, 19)
                .addComponent(LabelTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFormattedTextField3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TextFieldTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TextFieldFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void borrar() {
            TextFieldNombre.setText("");
            TextFieldVar.setText("");
            TextFieldCorreo.setText("");
            TextFieldContraseña.setText("");
            TextFieldTitular.setText("");
            TextFieldCalle.setText("");
            jFormattedTextField2.setText("");
            TextFieldWeb.setText("");
            jFormattedTextField3.setText("");
            FormattedTextFieldTelefono.setText("");
            jFormattedTextField1.setText("");
            TextFieldCiudad.setText("");
       }

    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        principal.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void TextFieldBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldBorrarMouseClicked
        // TODO add your handling code here:
        borrar();
    }//GEN-LAST:event_TextFieldBorrarMouseClicked

    private void ComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxTipoActionPerformed
        // TODO add your handling code here:
        tipo = (String) ComboBoxTipo.getSelectedItem();
        if (tipo.equals("Empresa")) {
            LabelVar.setText("CIF");
            LabelWeb.setVisible(true);
            TextFieldWeb.setVisible(true);
            
        }
        else {
            LabelVar.setText("DNI");
            LabelWeb.setVisible(false);
            TextFieldWeb.setVisible(false);

        }
    }//GEN-LAST:event_ComboBoxTipoActionPerformed

    private void TextFieldRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TextFieldRegistrarMouseClicked
        tipo = (String) ComboBoxTipo.getSelectedItem();

        try {
            // TODO add your handling code here:
            clientes = Metodos.LeerClientes();
        } catch (IOException ex) {
            Logger.getLogger(MenuRegistrar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MenuRegistrar.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        String cif = TextFieldVar.getText();
        String nombre = TextFieldNombre.getText();
        String correo = TextFieldCorreo.getText();
        String clave = TextFieldContraseña.getText();
        String telefono = FormattedTextFieldTelefono.getText();
        String calle = TextFieldCalle.getText();
        String numeroCalle = jFormattedTextField1.getText();
        String codigoPostal = jFormattedTextField2.getText();
        String ciudad = TextFieldCiudad.getText();
        String titularTarjeta = TextFieldTitular.getText();
        String numeroTarjeta = jFormattedTextField3.getText();
        String fechaCaducidadTxt = (String) TextFieldFecha.getValue();
        String web = TextFieldWeb.getText();
        
        
        
        

        if (cif.isEmpty() || nombre.isEmpty() || correo.isEmpty() || clave.isEmpty() || telefono.isEmpty()
                || calle.isEmpty() || numeroCalle.isEmpty() || codigoPostal.isEmpty() || ciudad.isEmpty()) {
            
            JOptionPane.showMessageDialog(rootPane, "Rellene todos los campos."); 
            
        } else if (fechaCaducidadTxt == null) {
            
            JOptionPane.showMessageDialog(rootPane, "Introduce una fecha válida.");
         
        } else if ((codigoPostal.length() < 5) || (Integer.parseInt(codigoPostal) <0)) {
            
            JOptionPane.showMessageDialog(rootPane, "Introduce un código postal válido.");
            
        } else if ((numeroTarjeta.length() != 16) || (Long.parseLong(numeroTarjeta)<0 )) {
            
            JOptionPane.showMessageDialog(rootPane, "Introduce un número de tarjeta válido.");
            
        } else if (((Metodos.consultaClientePorCorreo(correo, clientes) != null))) {
            
            JOptionPane.showMessageDialog(rootPane, "Cuenta ya registrada.");
            
        } else if (Integer.parseInt(telefono)<0) {    
            
                JOptionPane.showMessageDialog(rootPane, "Introduce un telefono válido.");
                
        } else if (Integer.parseInt(numeroCalle)< 0) {
            
                JOptionPane.showMessageDialog(rootPane, "Introduce un numero de calle válido.");
                
        } else {
            
            String[] partes = fechaCaducidadTxt.split("/");
            int d1 = Integer.parseInt(partes[0]);
            int m1 = Integer.parseInt(partes[1]);
            int a1 = Integer.parseInt(partes[2]);

            if (!buenaFecha(d1, m1, a1)) {
                JOptionPane.showMessageDialog(rootPane, "Introduce una fecha válida.");
            } else {
                LocalDate fechaCaducidad = LocalDate.of(a1, m1, d1);

                if (tipo.equals("Particular")) {
                    String dni = TextFieldVar.getText();

                    Particular par = new Particular(dni, nombre, correo, clave, calle, Integer.parseInt(numeroCalle.trim()), codigoPostal, ciudad, telefono,
                            titularTarjeta, numeroTarjeta, fechaCaducidad);

                    System.out.println(par.toString() + "|Particular");
                    clientes.add(par);
                    Metodos.RegistrarClientes(clientes);
                    JOptionPane.showMessageDialog(rootPane, "Particular registrado correctamente.");
                    borrar();
                    
                    
                } else if (tipo.equals("Empresa")) {
                    Empresa em = new Empresa(cif, nombre, correo, clave, calle, Integer.parseInt(numeroCalle), codigoPostal, ciudad, telefono, web,
                            titularTarjeta, numeroTarjeta, fechaCaducidad);

                    if (web.isEmpty()) {
                        JOptionPane.showMessageDialog(rootPane, "Rellene todos los campos.");
                    }
                    else {
                    System.out.println(em.toString() + "|Empresa");
                    clientes.add(em);
                    Metodos.RegistrarClientes(clientes);
                    JOptionPane.showMessageDialog(rootPane, "Empresa registrada correctamente.");
                    borrar();
                    
                    }
                }
            }
        }
    }//GEN-LAST:event_TextFieldRegistrarMouseClicked

    private void TextFieldRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldRegistrarActionPerformed

    /**Argumentos a usar
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxTipo;
    private javax.swing.JFormattedTextField FormattedTextFieldTelefono;
    private javax.swing.JLabel LabelContraseña;
    private javax.swing.JLabel LabelCorreo;
    private javax.swing.JLabel LabelDireccion;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelRegistrarse;
    private javax.swing.JLabel LabelTarjeta;
    private javax.swing.JLabel LabelTelefono;
    private javax.swing.JLabel LabelVar;
    private javax.swing.JLabel LabelWeb;
    private javax.swing.JTextField TextFieldBorrar;
    private javax.swing.JTextField TextFieldCalle;
    private javax.swing.JTextField TextFieldCiudad;
    private javax.swing.JTextField TextFieldContraseña;
    private javax.swing.JTextField TextFieldCorreo;
    private javax.swing.JFormattedTextField TextFieldFecha;
    private javax.swing.JTextField TextFieldNombre;
    private javax.swing.JTextField TextFieldRegistrar;
    private javax.swing.JTextField TextFieldTitular;
    private javax.swing.JTextField TextFieldVar;
    private javax.swing.JTextField TextFieldWeb;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}

